// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cswhdcullearorgtkolh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzd2hkY3VsbGVhcm9yZ3Rrb2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MTMwNTAsImV4cCI6MjA2MTM4OTA1MH0.Eiph9wYVt1lui-BAfCNeQLJOwStv53oTMxNG512kDgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);